spec: "1.0"

readOnlyProps:
    name        : '*IDN'

readWriteProps:
    startwl     : :SENS:WAV:STAR
    stopwl      : :SENS:WAV:STOP
    span        : :SENS:WAV:SPAN
    centerwl    : :SENS:WAV:CENT
    bandwidth   : :SENS:BAND:RES
    points      : :SENS:SWE:POIN
    sweepmode   : :INIT:SMOD 

readBinaryTraces:
    wavelength  :
     command    : :TRAC:X
     suffix     : TRA
    data        :
     command    : :TRAC:Y
     suffix     : TRA