spec: "1.0"

readOnlyProps:
    name        : '*IDN'

readWriteProps:
    startwl     :
        command     : :SENS:WAV:STAR
        min_value   : 600.0e-9
        max_value   : 1700.0e-9
    stopwl      :
        command     : :SENS:WAV:STOP
        min_value   : 600.0e-9
        max_value   : 1700.0e-9
    sweepmode   : 
        command     : :INIT:SMOD 
        doc_string  : 'Sets sweepmode: 1 = Single, 2 = Repeat, 3 = Auto, Needs a self.start_sweep() to take effect'
        allowed_values: [1,2,3]
        
    span        : :SENS:WAV:SPAN
    centerwl    : :SENS:WAV:CENT
    bandwidth   : :SENS:BAND:RES
    points      : :SENS:SWE:POIN
    


readBinaryTraces:
    wavelength  :
     command    : :TRAC:X
     suffix     : TRA
    data        :
     command    : :TRAC:Y
     suffix     : TRA
    TraceA      :
     command    : :TRAC:Y
     suffix     : TRA
    wlA  :
     command    : :TRAC:X
     suffix     : TRA
    TraceB        :
     command    : :TRAC:Y
     suffix     : TRB
    wlB  :
     command    : :TRAC:X
     suffix     : TRB
    wlC  :
     command    : :TRAC:X
     suffix     : TRC
    TraceC        :
     command    : :TRAC:Y
     suffix     : TRC
    wlD  :
     command    : :TRAC:X
     suffix     : TRD
    TraceD        :
     command    : :TRAC:Y
     suffix     : TRD
    wlE  :
     command    : :TRAC:X
     suffix     : TRE
    TraceE        :
     command    : :TRAC:Y
     suffix     : TRE
    wlF  :
     command    : :TRAC:X
     suffix     : TRF
    TraceF        :
     command    : :TRAC:Y
     suffix     : TRF
    wlG  :
     command    : :TRAC:X
     suffix     : TRG
    TraceG        :
     command    : :TRAC:Y
     suffix     : TRG